src/components/Button/Button.jsx
src/components/Button/Button.scss
src/styles/common.scss
src/styles/reset.scss
src/styles/variable.scss

UI 공통 색상을 정해 버튼을 컴포넌트로 만들었습니다.
팀원들과 공통 버튼을 공유하여 헷갈리지 않게 작업을 할 수 있습니다.
<br />
공통 버튼 추가
- 공통 버튼 추가
- props : class, disabled, onclick
<br />
<br />
-
<br />
<br />

[50기 홍지영] style : 버튼 피드백 수정

---

src/pages/Payment/Payment.jsx
src/pages/Payment/Payment.scss
src/pages/Payment/components/Ordersinfo.jsx
src/pages/Payment/components/Ordersinfo.scss

상품 결제하기 페이지
유저는 현재 예매한 상품의 세부 정보를 확인하거나 결제할 수 있는 페이지를 볼 수 있게 됩니다.
<br />
결제 페이지 UI 추가
- 예약 상품의 세부 정보를 확인하는 부분과 토스 api로 연동할 위치에 css를 적용했습니다.
- 결제 페이지를 구성하는 일부 레이아웃 컴포넌트를 추가했습니다.
( OrdersInfo 컴포넌트에서 props로 사용하는 부분
title : 예약한 공연 명 
imgUrl : 예약한 공연 이미지 url
time: 예약한 공연 시간 (ex : 공연시간 150분)
date: 예약한 공연 날짜 (ex: 2023년 5월 5일 오후 2시)
location: 예약한 공연의 위치 (ex: 수원아트센터)
seatNumber: 예약한 좌석 번호 (ex: R열 35번)
totalPrice: 총 결제할 금액  (ex:70,000))
<br />
<br />
-
<br />
- map과 배열, props를 이용해 예약 상세정보 부분을 구현할 수 있었습니다.
- scss의 네스팅 방식과 선택자 활용을 통해 효과적으로 scss를 다룰 수 있었습니다.
<br />

[50기 박주희] style: 피드백 반영

---

src/components/Button/Button.jsx

button {children} 수정
props 쓰지 않고 바로 텍스트 입력 가능
<br />
button {children} 수정
<br />
<br />
-
<br />
<br />

[50기 홍지영] fix : 버튼 text 수정

---

src/Router.jsx
src/components/Layout/Layout.jsx
src/components/Layout/Layout.scss
src/styles/variable.scss

레이아웃 width 값 수정, 공통 밝은 회색 추가
팀원들에게 공통 width, 컬러값 추가
<br />
공통 layout width 추가
공통 button color 추가
<br />
<br />
<br />
<br />

[50기 홍지영] style : 레이아웃 수정, 공통 컬러 추가

---

src/components/Layout/Layout.scss

<br />
(예시) 로그인 기능 추가
<br />
<br />
-
<br />
<br />

[50기 홍지영] style : container width 수정

---

src/pages/Admin/Admin.jsx
src/pages/Admin/Admin.scss
src/pages/Admin/components/Dashboard/Dashboard.jsx
src/pages/Admin/components/Dashboard/Dashboard.scss
src/pages/Admin/components/List/List.jsx
src/pages/Admin/components/List/List.scss
src/pages/Admin/components/Post/Post.jsx
src/pages/Admin/components/Post/Post.scss

관리자 페이지
이벤트 등록, 이벤트 리스트 화면 추가
대시보드 추가
관리자는 편리하게 이벤트 리스트를 등록할 수 있고, 등록한 이벤트 리스트를 관리할 수 있다.
관리자는 고객이 구매한 리스트를 확인할 수 있다.
<br />
화면 이동 추가
<br />
<br />
<br />
<br />

[50기 홍지영] fix : 피드백 반영

---

src/components/Button/Button.scss

<br />
(예시) 로그인 기능 추가
<br />
<br />
-
<br />
<br />

[50기 홍지영] style : 버튼 비활성화 커서 변경

---

src/pages/Detail/Detail.jsx
src/pages/Detail/Detail.scss
src/pages/Detail/components/Datepicker/Datepicker.jsx
src/pages/Detail/components/Datepicker/Datepicker.scss

데이터피커 관람 시간과 끝 시간 추가
타임키퍼 추가
유저는 관람을 원하는 날과 시간에 신청할 수 있다.
<br />
(예시) 로그인 기능 추가
<br />
<br />
<br />
<br />

[50기 홍지영] fix : datepicker 시작과 끝 날짜 추가, timepicker 추가

---

src/pages/Admin/components/Post/Post.jsx

카테고리 선택
카테고리 선택
<br />
(예시) 로그인 기능 추가
<br />
<br />
<br />
<br />

[50기 홍지영] fix : 카테고리 추가

---

src/config.js
src/pages/Detail/Detail.jsx
src/pages/Detail/Detail.scss
src/pages/Detail/components/Datepicker/Datepicker.jsx
src/pages/Detail/components/Datepicker/Datepicker.scss

유저는 날짜를 선택할 수 있고 그 날짜에 맞는 시간을 선택할 수 있다.
유저는 날짜를 선택할 수 있고 그 날짜에 맞는 시간을 선택할 수 있다.
<br />
달력 기능 추가
- 달력 기간 받아와서 클릭하면 그에 맞는 시간이 나타남
<br />
<br />
<br />
<br />

[50기 홍지영] feat : 달력 기능 추가

---

src/pages/Detail/components/Seat/Seat.jsx

<br />
(예시) 로그인 기능 추가
<br />
<br />
-
<br />
<br />

[50기 홍지영] fix : 피드백 반영(disabled 경우 기능이 다른 브랜치에 있어 머지 후 추가 가능)

---

src/config.js
src/pages/Detail/Detail.jsx
src/pages/Detail/Detail.scss
src/pages/Detail/components/Seat/Seat.jsx
src/pages/Detail/components/Seat/Seat.scss

<br />
(예시) 로그인 기능 추가
<br />
<br />
-
<br />
<br />

[50기 홍지영] style : ui 수정, 상세 데이터 불러오기 테스트, 결제 기능 추가 예정

---

src/pages/Detail/components/Seat/Seat.jsx
src/pages/Detail/components/Seat/Seat.scss

<br />
(예시) 로그인 기능 추가
<br />
<br />
-
<br />
<br />

[50기 홍지영] feat : 좌석  disabled 경우 추가

---

src/Router.jsx
src/pages/Admin/components/Dashboard/Dashboard.jsx
src/pages/Admin/components/List/List.jsx
src/pages/Admin/components/Post/Post.jsx

<br />
(예시) 로그인 기능 추가
<br />
<br />
-
<br />
<br />

[50기 홍지영] fix : 관리자 페이지 수정

---

src/components/Header/Header.jsx
src/components/Header/Header.scss
src/config.js
src/pages/Admin/components/Dashboard/Dashboard.jsx
src/pages/Admin/components/List/List.jsx
src/pages/Admin/components/Post/Post.jsx
src/pages/Detail/Detail.jsx
src/pages/Detail/components/Seat/Seat.jsx
src/pages/Login/Login.jsx
src/pages/Main/Main.jsx
src/pages/Main/Main.scss
src/pages/MyPage/MyPage.jsx
src/pages/MyPage/components/ProfileEdit/ProfileEdit.jsx
src/pages/Payment/Payment.jsx
src/pages/Payment/components/PriceArea/PriceArea.jsx
src/pages/kakao/KaKaoLogin.jsx

<br />
(예시) 로그인 기능 추가
<br />
<br />
-
<br />
<br />

[1차 병합 수정]

---

src/config.js
src/pages/Detail/Detail.jsx
src/pages/Detail/components/Location/Location.jsx
src/pages/Detail/components/Seat/Seat.jsx
src/pages/Detail/components/Seat/Seat.scss

<br />
(예시) 로그인 기능 추가
<br />
<br />
-
<br />
<br />

fix : 상세 수정

---

src/config.js
src/pages/Admin/components/Dashboard/Dashboard.jsx
src/pages/Admin/components/Dashboard/Dashboard.scss
src/pages/Admin/components/List/List.jsx
src/pages/Admin/components/Post/Post.jsx

<br />
(예시) 로그인 기능 추가
<br />
<br />
-
<br />
<br />

fix : admin 수정

---

src/pages/Admin/components/Dashboard/Dashboard.jsx
src/pages/Admin/components/Dashboard/Dashboard.scss

<br />
(예시) 로그인 기능 추가
<br />
<br />
-
<br />
<br />

style : 대시보드 수정

---

src/components/Header/Header.jsx

<br />
(예시) 로그인 기능 추가
<br />
<br />
-
<br />
<br />

fix : admin 로그인 수정

---

src/components/Header/Header.jsx
src/pages/Detail/components/Seat/Seat.jsx

<br />
(예시) 로그인 기능 추가
<br />
<br />
-
<br />
<br />

fix: 마이페이지 링크, 좌석 헤더값 수정

---

src/pages/Main/Main.jsx
src/pages/Main/Main.scss

<br />
(예시) 로그인 기능 추가
<br />
<br />
-
<br />
<br />

Main login final
